package com.frank.massageinstrument.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.frank.massageinstrument.entity.AcupointBean;
import com.frank.massageinstrument.entity.AcupointParamBean;

import com.frank.massageinstrument.db.AcupointBeanDao;
import com.frank.massageinstrument.db.AcupointParamBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig acupointBeanDaoConfig;
    private final DaoConfig acupointParamBeanDaoConfig;

    private final AcupointBeanDao acupointBeanDao;
    private final AcupointParamBeanDao acupointParamBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        acupointBeanDaoConfig = daoConfigMap.get(AcupointBeanDao.class).clone();
        acupointBeanDaoConfig.initIdentityScope(type);

        acupointParamBeanDaoConfig = daoConfigMap.get(AcupointParamBeanDao.class).clone();
        acupointParamBeanDaoConfig.initIdentityScope(type);

        acupointBeanDao = new AcupointBeanDao(acupointBeanDaoConfig, this);
        acupointParamBeanDao = new AcupointParamBeanDao(acupointParamBeanDaoConfig, this);

        registerDao(AcupointBean.class, acupointBeanDao);
        registerDao(AcupointParamBean.class, acupointParamBeanDao);
    }
    
    public void clear() {
        acupointBeanDaoConfig.clearIdentityScope();
        acupointParamBeanDaoConfig.clearIdentityScope();
    }

    public AcupointBeanDao getAcupointBeanDao() {
        return acupointBeanDao;
    }

    public AcupointParamBeanDao getAcupointParamBeanDao() {
        return acupointParamBeanDao;
    }

}
